### ISSUE TITLE
remove eslint plugin jsx-a11y

### ISSUE THREAD

**Issue by chrisvaillancourt** [chrisvaillancourt/website#9]
The [jsx-a11y plugin](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y) throws an unhandled exception when used in a `.astro` component.

### ESLint logs

```
[Info  - 7:32:55 PM] ESLint server is starting
[Info  - 7:32:55 PM] ESLint server running in node v16.13.2
[Info  - 7:32:55 PM] ESLint server is running.
[Info  - 7:32:56 PM] ESLint library loaded from: /website/node_modules/.pnpm/eslint@8.22.0/node_modules/eslint/lib/api.js
[Error - 7:32:59 PM] ESLint stack trace:
[Error - 7:32:59 PM] Error: The prop must be a JSXAttribute collected by the AST parser.
Occurred while linting /website/src/components/Link.astro:6
Rule: "jsx-a11y/anchor-is-valid"
    at propName (/website/node_modules/.pnpm/jsx-ast-utils@3.3.3/node_modules/jsx-ast-utils/lib/propName.js:14:11)
    at /website/node_modules/.pnpm/jsx-ast-utils@3.3.3/node_modules/jsx-ast-utils/lib/getProp.js:50:58
    at Array.find (<anonymous>)
    at getProp (/website/node_modules/.pnpm/jsx-ast-utils@3.3.3/node_modules/jsx-ast-utils/lib/getProp.js:43:30)
    at /website/node_modules/.pnpm/eslint-plugin-jsx-a11y@6.6.1_eslint@8.22.0/node_modules/eslint-plugin-jsx-a11y/lib/rules/anchor-is-valid.js:66:43
    at Array.map (<anonymous>)
    at JSXOpeningElement (/website/node_modules/.pnpm/eslint-plugin-jsx-a11y@6.6.1_eslint@8.22.0/node_modules/eslint-plugin-jsx-a11y/lib/rules/anchor-is-valid.js:65:38)
    at ruleErrorHandler (/website/node_modules/.pnpm/eslint@8.22.0/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /website/node_modules/.pnpm/eslint@8.22.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```

### Astro component

```
---
export type Props = astroHTML.JSX.AnchorHTMLAttributes;
const { href, ...attrs } = Astro.props as Props;
---

<a {href} {...attrs}>
  <slot />
</a>

```

**Comment by chrisvaillancourt** [comment]
closed by 4928bffb823399c06e46933ccef4f5df66b242c6.
